"""empty message

Revision ID: 61945d75eebe
Revises: 
Create Date: 2021-08-23 13:15:40.811461

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '61945d75eebe'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('produk',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nama', sa.String(), nullable=True),
    sa.Column('harga', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.SmallInteger(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('provinsi',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nama', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=True),
    sa.Column('last_name', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('phone_no', sa.String(), nullable=True),
    sa.Column('provinsi_id', sa.Integer(), nullable=True),
    sa.Column('kabupaten_id', sa.Integer(), nullable=True),
    sa.Column('kecamatan_id', sa.Integer(), nullable=True),
    sa.Column('kelurahan_id', sa.BigInteger(), nullable=True),
    sa.Column('address', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('kabupaten',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('provinsi_id', sa.Integer(), nullable=True),
    sa.Column('nama', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['provinsi_id'], ['provinsi.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('kecamatan',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kabupaten_id', sa.Integer(), nullable=True),
    sa.Column('nama', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['kabupaten_id'], ['kabupaten.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('kelurahan',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('kecamatan_id', sa.Integer(), nullable=True),
    sa.Column('nama', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['kecamatan_id'], ['kecamatan.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('kelurahan')
    op.drop_table('kecamatan')
    op.drop_table('kabupaten')
    op.drop_table('user')
    op.drop_table('provinsi')
    op.drop_table('produk')
    # ### end Alembic commands ###
