"""empty message

Revision ID: a42fdf690b3c
Revises: 61945d75eebe
Create Date: 2021-08-23 13:31:44.223104

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a42fdf690b3c'
down_revision = '61945d75eebe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('produk', 'is_active')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('produk', sa.Column('is_active', sa.SMALLINT(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
