"""empty message

Revision ID: e55894d3e09b
Revises: a42fdf690b3c
Create Date: 2021-08-23 21:10:02.866211

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e55894d3e09b'
down_revision = 'a42fdf690b3c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('order',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.String(length=255), nullable=True),
    sa.Column('buyer_id', sa.Integer(), nullable=True),
    sa.Column('approval_code', sa.String(length=255), nullable=True),
    sa.Column('transaction_time', sa.DateTime(), nullable=True),
    sa.Column('gross_amount', sa.Float(), nullable=True),
    sa.Column('currency', sa.String(length=255), nullable=True),
    sa.Column('payment_type', sa.String(length=255), nullable=True),
    sa.Column('signature_key', sa.String(length=255), nullable=True),
    sa.Column('status_code', sa.String(length=255), nullable=True),
    sa.Column('transaction_id', sa.String(length=255), nullable=True),
    sa.Column('transaction_status', sa.String(length=255), nullable=True),
    sa.Column('fraud_status', sa.String(length=255), nullable=True),
    sa.Column('settlement_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('order')
    # ### end Alembic commands ###
